### ISSUE TITLE
README.md: Code blocks are not being syntax higlighted

### ISSUE THREAD

**Issue by gcarreno** [ezlage/HyperX#2]
Boas Ezequiel(@ezlage),

When you know the type of code in your code blocks, you have to mention said type after the first triple backtick (\`\`\`) like this:

\`\`\`pascal
begin
  ivar:= 1;
  svar:= 'Value';
{ Código em Object Pascal/Delphi/Pascal }
end;
\`\`\`
```pascal
begin
  ivar:= 1;
  svar:= 'Value';
{ Código em Object Pascal/Delphi/Pascal }
end;
```

or 

\`\`\`sql
Select * from table where field = value limit 10;
\`\`\`
```sql
Select * from table where field = value limit 10;
```

or

\`\`\`ini
[Section]
Name=value
Foo=bar
\`\`\`
```ini
[Section]
Name=value
Foo=bar
```

I can dig a bit around the Markdown docs to give you the link of all the languages/file types that the GitHub flavour of Markdown supports, ok? Just let me know!!

(Grande abraço)
Cheers,
Gus

PS: 
> Não resisti: [Creating and highlighting code blocks](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks)
> Bem no fim tem links para o Linguist, que eu presumo seja quem trata da coloração de código.
> De novo, grande abraço!!

**Comment by ezlage** [comment]
Hello Gustavo! How are you?

I applied the suggested modifications and updated the repository.

I'm new here, so thank you for sharing your knowledge! I really appreciate it!

Until next time!

**Comment by gcarreno** [comment]
Hey Ezequiel(@ezlage):

> Hello Gustavo! I hope you're well!

I'm fine, thank you very much!!

> I applied the suggested modifications and updated the repository.

That is AWESOME, thank you so very much!!

> I'm new here, so thank you for sharing your knowledge. I really appreciate it!

I'm also not that experienced here but I have a passion to disseminate my small knowledge to whom ever I can!

(Grande abraço)
Cheers,
Gus
